import type { Database, Json } from "@repo/types";

/**
 * Convenience row/insert/update helpers over the generated `public` schema.
 * `Database` is generated by `bun run generate-types` into `@repo/types` — never
 * hand-write row shapes; derive them here, e.g. `Tables<"profiles">`.
 */
type Public = Database["public"];
type PublicRelations = Public["Tables"] & Public["Views"];

/** Row type of a `public` table or view, e.g. `Tables<"profiles">`. */
export type Tables<Name extends keyof PublicRelations> = PublicRelations[Name]["Row"];

/** Insert payload of a `public` table, e.g. `TablesInsert<"profiles">`. */
export type TablesInsert<Name extends keyof Public["Tables"]> = Public["Tables"][Name]["Insert"];

/** Update payload of a `public` table, e.g. `TablesUpdate<"profiles">`. */
export type TablesUpdate<Name extends keyof Public["Tables"]> = Public["Tables"][Name]["Update"];

/** A `public` enum, e.g. `Enums<"user_role">`. */
export type Enums<Name extends keyof Public["Enums"]> = Public["Enums"][Name];

export type { Database, Json };
